#!/bin/sh
#
w=" GitHub\n Wikipedia\n YouTube\nGmail\nAniList\nhorriblesubs\nschool\njstris"
c=$(echo -e $w | dmenu -c -p ' Bookmark' -i -l 10)
[ -z "$c" ] && exit
case $c in
" GitHub") firefox https://github.com/giabao141104/;;
" Wikipedia") firefox https://en.wikipedia.org;;
" YouTube") firefox https://youtube.com;;
Gmail) firefox https://gmail.com;;
AniList) firefox https://anilist.co/;;
horriblesubs) firefox https://horriblesubs.info/;;
school) firefox https://thptgiadinh.hcm.edu.vn;;
jstris) firefox https://jstris.jezevec10.com;;
esac
