#!/bin/sh
while true; do
  xsetroot -name "$(echo $(echo $(echo "" ; cat ~/document/speedtest-result | awk '{print $5,$6}') ; echo $(echo "" ; cat ~/document/speedtest-result | awk '{print $8,$9}') ; echo "   Used:" ; echo $(df -H --block-size M /dev/sda3 | tail -1 | awk '{print $3}' ; echo " Packages:";pacman -Q | wc -l) ; echo "" ; pamixer --get-volume-human ; date +" [%H:%M] - %A, %B %d, %Y "))"
  sleep 1s
done
